// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import CommentController from "./comment_controller"
application.register("comment", CommentController)

import InsertInListController from "./insert_in_list_controller"
application.register("insert-in-list", InsertInListController)

import PlacesController from "./places_controller"
application.register("places", PlacesController)
